version: '3'
services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_network
  flaskapi:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_network
      - api_network
    depends_on:
      - db
networks:
  db_network:
    driver: bridge
  api_network:
    driver: bridge
volumes:
  dbdata: